inference:
  batch_size: 1
  max_length: 512
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  num_return_sequences: 1
  safety_threshold: 0.95
  max_response_time: 0.2
  cache_size: 1000
  fallback_strategies:
    - "default_response"
    - "safe_mode"
    - "operator_intervention"